#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Expand grammar_mcq_a2.js: units 1-12(+),14. Inserted items end with ',' (valid JS)."""
import re, collections

PATH = r"C:/Users/Samet Tıraşoğlu.DESKTOP-V1NEC06/synth-app/languago-platform/src/data/grammar_mcq_a2.js"
NEW = {}
new = NEW

new["a2-01"] = [
("Look! The children ___ in the garden.", ["play","are playing","playing","plays"], 1, None),
("She ___ dinner right now.", ["cooks","is cooking","cook","cooking"], 1, None),
("I ___ for the bus at the moment.", ["wait","am waiting","waiting","waits"], 1, None),
("They ___ a new house these days.", ["are building","build","builds","building"], 0, None),
("Be quiet! The baby ___ .", ["sleeps","is sleeping","sleep","sleeping"], 1, None),
("We ___ TV now.", ["are watching","watch","watches","watching"], 0, None),
("He ___ his homework at the moment.", ["is doing","do","does","doing"], 0, None),
("What ___ you doing now?", ["are","is","do","does"], 0, None),
("It ___ outside. Take an umbrella.", ["rains","is raining","rain","raining"], 1, None),
("My mother ___ the flowers in the kitchen now.", ["waters","is watering","water","watering"], 1, None),
("Listen! The birds ___ .", ["sing","are singing","sings","singing"], 1, None),
("They ___ English at this school these days.", ["learn","are learning","learns","learning"], 1, None),
("The phone ___ . Can you answer it?", ["is ringing","rings","ring","ringing"], 0, None),
("I ___ a letter to my friend at the moment.", ["write","am writing","writes","writing"], 1, None),
("She ___ a red dress today.", ["wears","is wearing","wear","wearing"], 1, None),
("The students ___ an exam right now.", ["take","are taking","takes","taking"], 1, None),
]
new["a2-02"] = [
("I ___ to work every morning.", ["go","am going","going","goes"], 0, None),
("She ___ TV every evening.", ["watches","is watching","watch","watching"], 0, None),
("Look at him! He ___ very fast today.", ["runs","is running","run","running"], 1, None),
("We ___ bread at this bakery every week.", ["buy","are buying","buys","buying"], 0, None),
("Right now I ___ tea, but usually I drink coffee.", ["am drinking","drink","drinks","drinking"], 0, None),
("My brother ___ football on Fridays.", ["plays","is playing","play","playing"], 0, None),
("Now I ___ what you mean.", ["understand","am understanding","understanding","understands"], 0, None),
("She ___ for her keys right now.", ["looks","is looking","look","looking"], 1, None),
("Ice ___ when it is above zero.", ["melts","is melting","melt","melting"], 0, None),
("The sun ___ in the east.", ["rises","is rising","rise","rising"], 0, None),
("We ___ a test every month.", ["have","are having","having","has"], 0, None),
("He ___ coffee. He never drinks tea.", ["likes","is liking","like","liking"], 0, None),
("I ___ this soup delicious.", ["find","am finding","finding","finds"], 0, None),
("She ___ to music right now.", ["listens","is listening","listen","listening"], 1, None),
("They ___ in London at the moment.", ["live","are living","lives","living"], 1, None),
("The teacher ___ the lesson now.", ["explains","is explaining","explain","explaining"], 1, None),
]
new["a2-03"] = [
("We ___ to the cinema last night.", ["went","go","goed","going"], 0, None),
("She ___ a problem with her car yesterday.", ["had","has","haved","having"], 0, None),
("He ___ his keys on the table.", ["put","puts","putted","putting"], 0, None),
("I ___ my friend at the station yesterday.", ["met","meet","meeted","meeting"], 0, None),
("They ___ a great movie last weekend.", ["saw","see","sawed","seeing"], 0, None),
("She ___ a cake for the party.", ["made","make","maked","making"], 0, None),
("Last year we ___ to Italy.", ["traveled","travel","travels","traveling"], 0, None),
("He ___ up very early this morning.", ["woke","wakes","waked","waking"], 0, None),
("The teacher ___ the question two times.", ["repeated","repeats","repeat","repeating"], 0, None),
("My grandmother ___ me a letter last month.", ["sent","sends","send","sending"], 0, None),
("The children ___ in the park all afternoon.", ["played","plays","play","playing"], 0, None),
("I ___ a glass of water after the run.", ["drank","drink","drunk","drinking"], 0, None),
("The bus ___ at 8 this morning.", ["came","comes","comed","coming"], 0, None),
("He ___ his phone on the train.", ["left","leaves","leaved","leaving"], 0, None),
("We ___ to the radio last night.", ["listened","listen","listens","listening"], 0, None),
("She ___ her homework yesterday evening.", ["finished","finish","finishes","finishing"], 0, None),
]
new["a2-04"] = [
("___ she call you yesterday?", ["Did","Does","Do","Was"], 0, None),
("We ___ see our friends last weekend.", ["didn't","don't","doesn't","aren't"], 0, None),
("Why ___ you leave the party early?", ["did","do","does","are"], 0, None),
("He ___ his wallet at home this morning.", ["didn't bring","doesn't bring","didn't brought","don't bring"], 0, None),
("___ they finish the project yesterday?", ["Did","Do","Does","Were"], 0, None),
("She didn't ___ that book last year.", ["read","readed","reads","reading"], 0, None),
("Where ___ you go last summer?", ["did","do","does","were"], 0, None),
("I ___ the film because I was tired.", ["didn't watch","don't watch","didn't watched","not watch"], 0, None),
("___ your brother travel abroad last month?", ["Did","Does","Do","Was"], 0, None),
("We ___ visit the museum two days ago.", ["didn't","doesn't","don't","aren't"], 0, None),
("She ___ come to class last Monday.", ["didn't","doesn't","don't","isn't"], 0, None),
("___ you understand the lesson yesterday?", ["Did","Do","Does","Are"], 0, None),
("He ___ buy any milk because the shop was closed.", ["didn't","doesn't","don't","wasn't"], 0, None),
("We ___ go camping last summer.", ["didn't","don't","doesn't","aren't"], 0, None),
("___ your parents watch the match? Yes, they did.", ["Did","Do","Does","Were"], 0, None),
("Yesterday I ___ forget to call you.", ["didn't","don't","doesn't","am not"], 0, None),
]
new["a2-05"] = [
("I ___ travel to Trabzon next month.", ["am going to","going to","is going to","am go to"], 0, None),
("She ___ study medicine at university.", ["is going to","are going to","going to","is go to"], 0, None),
("We ___ have a party on Friday.", ["are going to","is going to","going to","are go to"], 0, None),
("He ___ buy a new phone.", ["is going to","are going to","are going","is go"], 0, None),
("Look at those clouds! It ___ rain.", ["is going to","are going to","going to","is go to"], 0, None),
("They ___ move to a bigger flat.", ["are going to","is going to","going to","are go to"], 0, None),
("What ___ you going to do tomorrow?", ["are","is","do","does"], 0, None),
("I'm going to ___ my room this afternoon.", ["clean","cleaning","cleans","cleaned"], 0, None),
("She ___ going to visit her aunt.", ["is","are","am","do"], 0, None),
("Are you going to ___ dinner with us?", ["have","having","has","had"], 0, None),
("We aren't going to ___ late.", ["be","being","is","are"], 0, None),
("He is going to ___ a doctor.", ["become","becoming","becomes","became"], 0, None),
("I'm going to ___ my Spanish next year.", ["improve","improving","improves","improved"], 0, None),
("They are going to ___ football after school.", ["play","playing","plays","played"], 0, None),
("She's going to ___ her car tomorrow.", ["wash","washing","washes","washed"], 0, None),
("We're going to ___ a DVD tonight.", ["watch","watching","watches","watched"], 0, None),
]
new["a2-06"] = [
("This street is ___ than that one.", ["narrower","more narrow","narrowest","most narrow"], 0, None),
("Spring is ___ than winter in my city.", ["warmer","more warm","warmest","most warm"], 0, None),
("This cafe is the ___ in town.", ["best","better","gooder","more good"], 0, None),
("My sister is ___ than me.", ["more patient","patienter","most patient","more patienter"], 0, None),
("This exam is ___ than the last one.", ["easier","more easy","easiest","most easy"], 0, None),
("That was the ___ day of my life.", ["happiest","more happy","happier","happiestly"], 0, None),
("Apples are ___ than bananas in my country.", ["cheaper","more cheap","cheapest","most cheap"], 0, None),
("He runs ___ than his brother.", ["faster","fastest","more fast","most fast"], 0, None),
("This problem is ___ than the first one.", ["harder","more hard","hardest","most hard"], 0, None),
("She is the ___ girl in our group.", ["friendliest","more friendly","friendlier","most friendlier"], 0, None),
("A car is ___ than a bicycle.", ["faster","fastest","more fast","most fast"], 0, None),
("This is the ___ dish in the restaurant.", ["most popular","more popular","popularer","popularest"], 0, None),
("My bag is ___ than yours.", ["lighter","more light","lightest","most light"], 0, None),
("Today is ___ than yesterday.", ["hotter","more hot","hottest","most hot"], 0, None),
("He is the ___ runner on the team.", ["slowest","more slow","slower","most slowly"], 0, None),
("This film is ___ than the one we saw last week.", ["funnier","more funny","funniest","most funny"], 0, None),
]
new["a2-07"] = [
("How ___ sugar do you want in your coffee?", ["much","many","some","any"], 0, None),
("How ___ eggs are there in the box?", ["many","much","some","any"], 0, None),
("How ___ rain fell last night?", ["much","many","some","any"], 0, None),
("How ___ days are there in a week?", ["many","much","some","any"], 0, None),
("How ___ time do we have?", ["much","many","some","any"], 0, None),
("How ___ people work here?", ["many","much","some","any"], 0, None),
("Too ___ salt is bad for you.", ["much","many","some","any"], 0, None),
("There are too ___ cars on this road.", ["many","much","some","any"], 0, None),
("I don't have very ___ homework today.", ["much","many","any","some"], 0, None),
("She doesn't have very ___ friends in this city.", ["many","much","any","some"], 0, None),
("I have ___ money in my wallet.", ["some","any","many","a"], 0, None),
("Can I get you ___ water?", ["some","many","much","an"], 0, None),
("There isn't very ___ butter left.", ["much","many","some","any"], 0, None),
("We haven't got very ___ tomatoes for the salad.", ["many","much","some","any"], 0, None),
("How ___ butter do you need for the cake?", ["much","many","some","any"], 0, None),
("How ___ mistakes did you find?", ["many","much","some","any"], 0, None),
]
new["a2-08"] = [
("My brother ___ cook very well.", ["can","cans","can to","can cooking"], 0, None),
("I ___ speak three languages.", ["can","cans","can to","am can"], 0, None),
("She ___ not come to the party.", ["can","is can","can to","cans"], 0, None),
("___ he swim across the lake?", ["Can","Cans","Can to","Does can"], 0, None),
("I'm sorry, I ___ hear you.", ["can't","cans","can't to","don't can"], 0, None),
("They ___ play chess.", ["can","cans","can to","can playing"], 0, None),
("___ we sit here? Yes, of course.", ["Can","Cans","Are","Do"], 0, None),
("You ___ leave now. I will finish.", ["can","can to","cans","canning"], 0, None),
("She can ___ Italian food.", ["cook","cooks","cooking","cooked"], 0, None),
("The baby ___ walk yet.", ["can't","is can","can to","don't can"], 0, None),
("Can you ___ me your phone?", ["give","gives","giving","gave"], 0, None),
("I can ___ this question easily.", ["answer","answers","answering","answered"], 0, None),
("We can't ___ late for the train.", ["be","being","been","are"], 0, None),
("___ you see the mountain from here?", ["Can","Cans","Can to","Do can"], 0, None),
("He can ___ a bike.", ["ride","rides","riding","rode"], 0, None),
("My sister can't ___ a car yet.", ["drive","drives","driving","drove"], 0, None),
]
new["a2-09"] = [
("We ___ the door last night.", ["didn't lock","don't lock","didn't locked","not lock"], 0,
 ["Correct: lock geçmiş olumsuz → did + yalın: didn't lock.","Geniş 'don't lock' 'last night' için değil.","did'den sonra geçmiş değil yalın gelir: didn't locked yanlış.","'not lock' yardımcısız geçmiş olamaz."]),
("He ___ his grandmother two days ago.", ["called","calls","is calling","calling"], 0,
 ["Correct: 'two days ago' → geçmiş called (düzenli -ed).","Geniş 'calls' geçmiş zamanla uymaz.","Şimdiki 'is calling' geçmiş için değil.","'calling' tek başına çekimli fiil olamaz."]),
("They ___ a lot of water after the game.", ["drank","drinks","drink","drinking"], 0,
 ["Correct: drink → drank düzensiz geçmiş.","Geniş 'drinks' 3. tekil + geçmiş değil.","Yalın 'drink' geçmiş bağlamla uymaz.","'drinking' tek başına ana fiil olamaz."]),
("Last night I ___ very well.", ["slept","sleeps","slepted","sleeping"], 0,
 ["Correct: sleep → slept düzensiz geçmiş.","Geniş 'sleeps' 'last night' ile uymaz.","'slepted' — slept zaten geçmiş; -ed eklenmez.","'sleeping' tek başına geçmiş veremez."]),
("She ___ her mother a present for the birthday.", ["bought","buys","buyed","buying"], 0,
 ["Correct: buy → bought düzensiz geçmiş.","Geniş 'buys' geçmiş için değil.","'buyed' — buy düzensizdir, -ed almaz.","'buying' tek başına ana fiil olamaz."]),
("They ___ to the zoo last Sunday.", ["went","goes","goed","going"], 0,
 ["Correct: go → went düzensiz geçmiş.","Geniş 'goes' 'last Sunday' ile uymaz.","'goed' — go düzensizdir.","'going' tek başına çekimli değil."]),
("I ___ a letter from my pen friend last week.", ["got","gets","gotted","getting"], 0,
 ["Correct: get → got düzensiz geçmiş.","Geniş 'gets' geçmiş için değil.","'gotted' — get düzensizdir.","'getting' ana fiil olamaz."]),
("He ___ a photo of the old castle.", ["took","takes","taked","taking"], 0,
 ["Correct: take → took düzensiz geçmiş.","Geniş 'takes' geçmiş için değil.","'taked' — take düzensizdir.","'taking' tek başına çekimli değil."]),
("We ___ home late last evening.", ["came","comes","camed","coming"], 0,
 ["Correct: come → came düzensiz geçmiş.","Geniş 'comes' 'last evening' ile uymaz.","'camed' — come düzensizdir.","'coming' tek başına geçmiş veremez."]),
("She ___ her book on the bus yesterday.", ["lost","loses","losed","losing"], 0,
 ["Correct: lose → lost düzensiz geçmiş.","Geniş 'loses' 'yesterday' ile uymaz.","'losed' — lose düzensizdir.","'losing' ana fiil olamaz."]),
("They ___ an interesting question to the teacher.", ["asked","asks","is asking","asking"], 0,
 ["Correct: ask düzenli geçmiş → asked.","Geniş 'asks' geçmiş için değil.","Şimdiki 'is asking' geçmiş bağlamla uymaz.","'asking' tek başına çekimli değil."]),
("I ___ your name, what is it again?", ["forgot","forgets","forgotted","forgetting"], 0,
 ["Correct: forget → forgot düzensiz geçmiş.","Geniş 'forgets' I öznesi ile uymaz.","'forgotted' — forget düzensizdir.","'forgetting' ana fiil olamaz."]),
("She ___ across the street very quickly.", ["ran","runs","runned","running"], 0,
 ["Correct: run → ran düzensiz geçmiş.","Geniş 'runs' geçmiş için değil.","'runned' — run düzensizdir.","'running' tek başına geçmiş veremez."]),
("We ___ a great time at the festival.", ["had","have","haved","having"], 0,
 ["Correct: have → had düzensiz geçmiş.","Geniş 'have' geçmiş için değil.","'haved' — have düzensizdir.","'having' tek başına ana fiil olamaz."]),
("He ___ the answer to every question.", ["knew","knows","knowed","knowing"], 0,
 ["Correct: know → knew düzensiz geçmiş.","Geniş 'knows' geçmiş için değil.","'knowed' — know düzensizdir.","'knowing' tek başına çekimli değil."]),
]
new["a2-10"] = [
("I ___ very happy to see you yesterday.", ["was","were","am","is"], 0,
 ["Correct: I + geçmiş 'yesterday' → was.","'were' you/we/they için; I ile değil.","Şimdiki 'am' 'yesterday' ile uymaz.","'is' 3. tekil şimdiki; I+geçmiş için değil."]),
("We ___ at the museum last Saturday.", ["were","was","are","is"], 0,
 ["Correct: we + geçmiş → were.","'was' I/he/she/it; we ile değil.","Şimdiki 'are' geçmiş için değil.","'is' çoğul+geçmiş için değil."]),
("The weather ___ very nice last weekend.", ["was","were","is","are"], 0,
 ["Correct: weather tekil + geçmiş → was.","'were' çoğul; weather için değil.","Şimdiki 'is' geçmiş için değil.","'are' tekil+geçmiş için değil."]),
("There ___ a big problem with the car.", ["was","were","are","be"], 0,
 ["Correct: 'a problem' tekil + geçmiş → was.","'were' çoğul; tekil için değil.","Şimdiki 'are' geçmiş için değil.","'be' çekimsiz kalıptır."]),
("The shops ___ closed yesterday.", ["were","was","are","is"], 0,
 ["Correct: shops çoğul + geçmiş → were.","'was' çoğul için değil.","Şimdiki 'are' 'yesterday' ile uymaz.","'is' çoğul için değil."]),
("He ___ sick last week.", ["was","were","is","be"], 0,
 ["Correct: he + geçmiş → was.","'were' he için değil.","Şimdiki 'is' geçmiş için değil.","'be' çekimsiz."]),
("My friends ___ at the cafe with me.", ["were","was","is","am"], 0,
 ["Correct: friends çoğul + geçmiş → were.","'was' çoğul için değil.","'is' çoğul+geçmiş için değil.","'am' I ile; friends için değil."]),
("The test ___ easy for everyone.", ["was","were","are","be"], 0,
 ["Correct: test tekil + geçmiş → was.","'were' çoğul için değil.","Şimdiki 'are' geçmiş için değil.","'be' çekimsiz."]),
("___ it cold in the classroom yesterday?", ["Was","Were","Is","Are"], 0,
 ["Correct: it tekil + soru geçmiş → Was.","'Were' it ile kullanılmaz.","Şimdiki 'Is' 'yesterday' ile uymaz.","'Are' it + geçmiş için değil."]),
("I thought you ___ at home.", ["was","am was","were","are"], 2,
 ["'Was' you ile kullanılmaz; I/he/she/it içindir.","'am was' çift çekim, gramer dışı.","Correct: you + geçmiş → were.","Şimdiki 'are' geçmiş bağlamla uymaz."]),
("There ___ two birds on the tree.", ["were","was","is","am"], 0,
 ["Correct: two birds çoğul + geçmiş → were.","'was' çoğul için değil.","Şimdiki 'is' geçmiş için değil.","'am' I için; kuşlar için değil."]),
("Why ___ you angry at the meeting?", ["were","was","are","am"], 0,
 ["Correct: you + geçmiş soru → were.","'was' you ile değil.","Şimdiki 'are' geçmiş bağlamla uymaz.","'am' you için değil."]),
("The children ___ very noisy last night.", ["were","was","is","am"], 0,
 ["Correct: children çoğul + geçmiş → were.","'was' çoğul için değil.","Şimdiki 'is' geçmiş için değil.","'am' çoğul+geçmiş için değil."]),
("Her parents ___ at home that evening.", ["were","was","is","are"], 0,
 ["Correct: parents çoğul + geçmiş → were.","'was' çoğul için değil.","Şimdiki 'is' o akşam için değil.","Şimdiki 'are' geçmiş için değil."]),
("___ the lights on when you left?", ["Were","Was","Are","Am"], 0,
 ["Correct: lights çoğul + geçmiş soru → Were.","'Was' çoğul için değil.","Şimdiki 'Are' 'left' ile uymaz.","'Am' uygun değil."]),
]
new["a2-11"] = [
("I ___ breakfast at seven this morning.", ["had","have","haved","having"], 0,
 ["Correct: bu sabah (geçmiş) → had.","Geniş 'have' geçmiş için değil.","'haved' — have düzensizdir.","'having' tek başına ana fiil olamaz."]),
("She ___ to school by bus yesterday.", ["went","goes","goed","going"], 0,
 ["Correct: 'yesterday' → geçmiş went.","Geniş 'goes' geçmiş için değil.","'goed' — go düzensizdir.","'going' tek başına çekimli değil."]),
("They arrived here a week ___.", ["ago","last","before","since"], 0,
 ["Correct: 'a week ago' = bir hafta önce.","'last' öncesinde zaman ister (last week); sayı yok.","'before' sayı+ago kalıbında olmaz.","'since' başlangıç noktası ister."]),
("We ___ a new language last semester.", ["learned","learns","is learning","learning"], 0,
 ["Correct: 'last semester' geçmiş → learned.","Geniş 'learns' geçmiş için değil.","Şimdiki 'is learning' geçmiş için değil.","'learning' tek başına olamaz."]),
("He ___ his grandparents in spring.", ["visited","visits","is visiting","visit"], 0,
 ["Correct: geçmiş anlatı → visited.","Geniş 'visits' alışkanlık için; bitmiş olay değil.","Şimdiki 'is visiting' geçmiş için değil.","'visit' yalın çekimsiz."]),
("My father ___ me to the park yesterday.", ["took","takes","taked","taking"], 0,
 ["Correct: 'yesterday' → geçmiş took.","Geniş 'takes' geçmiş için değil.","'taked' — take düzensizdir.","'taking' tek başına ana fiil olamaz."]),
("She ___ a doctor last Monday because she was ill.", ["visited","visits","is visiting","visit"], 0,
 ["Correct: 'last Monday' geçmiş → visited.","Geniş 'visits' geçmiş için değil.","Şimdiki 'is visiting' geçmiş için değil.","'visit' yalın çekimsiz."]),
("We ___ in this hotel two years ago.", ["stayed","stays","stay","staying"], 0,
 ["Correct: 'two years ago' → stayed.","Geniş 'stays' geçmiş için değil.","'stay' çekimsiz.","'staying' tek başına ana fiil olamaz."]),
("He ___ his mistake and said sorry.", ["saw","sees","sawed","seeing"], 0,
 ["Correct: see → saw düzensiz geçmiş.","Geniş 'sees' geçmiş için değil.","'sawed' yanlış; see düzensiz.","'seeing' tek başına olamaz."]),
("They ___ dinner at a nice place last night.", ["had","have","haved","having"], 0,
 ["Correct: 'last night' → had.","Geniş 'have' geçmiş için değil.","'haved' — have düzensizdir.","'having' tek başına çekimli değil."]),
("I ___ the bus and walked to school.", ["missed","misses","am missing","missing"], 0,
 ["Correct: geçmiş sıralı anlatı → missed.","Geniş 'misses' geçmiş için değil.","Şimdiki 'am missing' geçmiş için değil.","'missing' tek başına olamaz."]),
("She ___ her umbrella on the bus.", ["left","leaves","leaved","leaving"], 0,
 ["Correct: leave → left düzensiz geçmiş.","Geniş 'leaves' geçmiş için değil.","'leaved' — leave düzensizdir.","'leaving' tek başına ana fiil olamaz."]),
("We ___ our homework before dinner.", ["finished","finishes","is finishing","finishing"], 0,
 ["Correct: geçmiş düzenli → finished.","Geniş 'finishes' geçmiş için değil.","Şimdiki 'is finishing' geçmiş için değil.","'finishing' tek başına olamaz."]),
("He ___ a very happy birthday party last year.", ["had","has","haved","having"], 0,
 ["Correct: 'last year' → had.","Geniş 'has' geçmiş için değil.","'haved' — have düzensizdir.","'having' tek başına çekimli değil."]),
]
new["a2-12"] = [
("Spring is ___ warm as summer in my city.", ["not as","more","the most","less"], 0,
 ["Correct: eşitsizlik → not as + sıfat + as.","'more warm as' — more as…as ile olmaz.","'the most' üstünlük; eşitlik kalıbı için değil.","'less' eksik; less warm than gerekir."]),
("My bag is ___ heavy as yours.", ["as","more","too","very"], 0,
 ["Correct: as + sıfat + as (eşitlik).","'more heavy as' — as…as'ta more olmaz.","'too heavy as' — too as…as ile olmaz.","'very heavy as' — very burada uymaz."]),
("This movie is ___ the book.", ["as good as","more good as","good as","as good than"], 0,
 ["Correct: as + good + as.","'more good as' — as…as'ta more olmaz.","'good as' — ilk 'as' eksik.","'as good than' — as…as'ta than olmaz."]),
("Her bag is ___ as mine.", ["not as large","more large as","largest as","large as"], 0,
 ["Correct: not as + sıfat + as.","'more large as' — as…as'ta more olmaz.","'largest as' üstünlük; eşitlik değil.","'large as' — ilk 'as' eksik."]),
("This road is ___ that one.", ["as long as","as long than","longer as","as longer as"], 0,
 ["Correct: as + long + as.","'as long than' — as…as'ta than olmaz.","'longer as' — comparative than ister.","'as longer as' — as…as arasına -er gelmez."]),
("His car is ___ expensive as ours.", ["not as","more","most","was"], 0,
 ["Correct: eşitsizlik → not as + expensive + as.","'more expensive as' — as…as'ta more olmaz.","'most' üstünlük; eşitlik için değil.","'was expensive as' — was burada uyumsuz."]),
("Today is ___ cold as yesterday.", ["as","more","most","than"], 0,
 ["Correct: as + cold + as.","'more cold as' — as…as'ta more olmaz.","'most cold as' — üstünlük değil.","'than' as…as'ta kullanılmaz."]),
("Her voice is ___ as sweet as a bird's.", ["almost","most","more","than"], 0,
 ["Correct: derece zarfı → almost as…as.","'most as sweet as' — üstünlük burada olmaz.","'more as' — more as…as ile olmaz.","'than' as…as yapısında yer almaz."]),
("This town is ___ as big as the capital.", ["about","than","most","more"], 0,
 ["Correct: yaklaşık eşitlik → about as…as.","'than big as' — yapı bozuk.","'most' eşitlik kalıbı için değil.","'more' as…as ile kullanılmaz."]),
("My room is ___ as quiet as yours.", ["just","most","more","than"], 0,
 ["Correct: tam eşitlik → just as…as.","'most quiet as' — üstünlük değil.","'more quiet as' — as…as'ta more olmaz.","'than' as…as'ta yer almaz."]),
("The test was ___ as hard as we expected.", ["not","more","most","too"], 0,
 ["Correct: eşitsizlik → not as + hard + as.","'more hard as' — more as…as ile olmaz.","'most' üstünlük; eşitlik için değil.","'too hard as' — too burada uymaz."]),
("This jacket is ___ as that one.", ["the same size","more same","samer","same size"], 0,
 ["Correct: eşitlik ifadesi → the same size as.","'more same' — same comparative almaz.","'samer' — same -er almaz.","'same size' — 'the' gereklidir."]),
]
new["a2-14"] = [
("I ___ lunch with my boss tomorrow.", ["am having","having","haveing","am have"], 0,
 ["Correct: planlı gelecek → am + having.","'having' tek başına çekimsiz.","'haveing' — have → having yazımı.","'am have' — -ing gerekli."]),
("She ___ a new job next month.", ["is starting","starts","is start","starting"], 0,
 ["Correct: program → is + starting.","Geniş 'starts' tekrar için; planlı değil.","'is start' — -ing gerekli.","'starting' tek başına olamaz."]),
("We ___ the train at nine tomorrow.", ["are catching","catch","cats","is catch"], 0,
 ["Correct: planlı → are catching.","Geniş 'catch' tekrar için; plan değil.","'cats' yazım/çekim yanlış.","'is catch' çoğul + -ing eksik."]),
("They ___ to the dentist next week.", ["are going","go","goes","is go"], 0,
 ["Correct: planlı → are going.","Geniş 'go' program için değil.","'goes' çoğul+planlı için değil.","'is go' — çoğul are + -ing gerekli."]),
("I ___ my cousin on Saturday.", ["am visiting","visit","visits","is visit"], 0,
 ["Correct: kişisel plan → am visiting.","Geniş 'visit' plan değil.","'visits' I + planlı için değil.","'is visit' — -ing gerekli."]),
("She ___ a new dress for the party.", ["is buying","buys","buy","buying"], 0,
 ["Correct: planlı → is buying.","Geniş 'buys' tekrar için; plan değil.","'buy' çekimsiz.","'buying' tek başına olamaz."]),
("We ___ our friends this evening.", ["are seeing","see","sees","is see"], 0,
 ["Correct: planlı buluşma → are seeing.","Geniş 'see' plan değil.","'sees' çoğul için değil.","'is see' — çoğul + -ing eksik."]),
("The train ___ at seven tomorrow morning.", ["is leaving","leaves","leave","leaving"], 0,
 ["Correct: çizelge → is leaving.","Geniş 'leaves' çizelge için değil.","'leave' çekimsiz.","'leaving' tek başına olamaz."]),
("I ___ to the hairdresser on Monday.", ["am going","go","goes","going"], 0,
 ["Correct: kişisel plan → am going.","Geniş 'go' planlı gelecek için değil.","'goes' I için değil.","'going' tek başına çekimsiz."]),
("They ___ a presentation next Friday.", ["are giving","give","gives","is give"], 0,
 ["Correct: planlı → are giving.","Geniş 'give' plan değil.","'gives' çoğul için değil.","'is give' — çoğul + -ing eksik."]),
("We ___ our uncle at the weekend.", ["are visiting","visit","visits","is visit"], 0,
 ["Correct: planlı → are visiting.","Geniş 'visit' plan değil.","'visits' çoğul için değil.","'is visit' — -ing gerekli."]),
("She ___ a cake for the party.", ["is making","makes","make","making"], 0,
 ["Correct: hazırlık → is making.","Geniş 'makes' tekrar için; plan değil.","'make' çekimsiz.","'making' tek başına olamaz."]),
("I ___ a doctor for my bad tooth.", ["am seeing","see","sees","seeing"], 0,
 ["Correct: planlı randevu → am seeing.","Geniş 'see' plan değil.","'sees' I + planlı için değil.","'seeing' tek başına olamaz."]),
("They ___ a new lesson this week.", ["are studying","study","studys","is study"], 0,
 ["Correct: planlı → are studying.","Geniş 'study' tekrar için; plan değil.","'studys' yazım yanlış (studies).","'is study' — çoğul + -ing eksik."]),
]

def js_str(s):
    return '"' + s.replace('\\','\\\\').replace('"','\\"').replace('\n',' ') + '"'

def fmt_u(u, item):
    q, opts, a, why = item
    why_part = '' if why is None else ', "why": [' + ", ".join(js_str(w) for w in why) + "]"
    return ('    { "q": %s, "options": [%s], "a": %d%s },' %
            (js_str(q), ", ".join(js_str(o) for o in opts), a, why_part))

src = open(PATH, encoding="utf-8").read()
for u, items in NEW.items():
    idx = src.index('  "' + u + '": [\n')
    close = src.index('\n  ],', idx)
    block = "\n".join(fmt_u(u, it) for it in items)
    src = src[:close] + "\n" + block + src[close:]

open(PATH, "w", encoding="utf-8").write(src)
print("pass-A done; total qs:", len(re.findall(r'"q":', src)))