// Languago — self-study content port script.
// Reads browser-global JS data files from the older english-word-coach Android
// assets and writes ES modules into src/data/<file> exporting the same data.
//
//   npm run port:content
//
// The source files are `window.X = <literal>;` browser globals (single-quoted,
// no module system, Turkish content). We only need to swap the `window.X =`
// assignment head for an `export const X =` — the body is already a valid JS
// expression (JSON literal or JS object literal). Each output module is then
// imported and sanity-checked.
//
// Source files are read-only and never modified.

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SRC =
  'C:/Users/Samet Tıraşoğlu.DESKTOP-V1NEC06/synth-app/english-word-coach/android/app/src/main/assets';
const DEST = join(ROOT, 'src/data');

// Source file (base name) → exported const name.
const FILES = [
  ['words.js', 'WORD_DATA'],
  ['grammar_a1.js', 'GRAMMAR_A1'],
  ['grammar_a2.js', 'GRAMMAR_A2'],
  ['grammar_b1.js', 'GRAMMAR_B1'],
  ['grammar_b2.js', 'GRAMMAR_B2'],
  ['grammar_mcq_a1.js', 'GRAMMAR_MCQ_A1'],
  ['grammar_mcq_a2.js', 'GRAMMAR_MCQ_A2'],
  ['grammar_mcq_b1.js', 'GRAMMAR_MCQ_B1'],
  ['grammar_mcq_b2.js', 'GRAMMAR_MCQ_B2'],
  ['readings_a1.js', 'READINGS_A1'],
  ['readings_a2.js', 'READINGS_A2'],
  ['readings_b1.js', 'READINGS_B1'],
  ['readings_b2.js', 'READINGS_B2'],
  ['readings_c1.js', 'READINGS_C1'],
  ['readings_c2.js', 'READINGS_C2'],
  ['readings_ielts.js', 'READINGS_IELTS'],
  ['readings_toefl.js', 'READINGS_TOEFL'],
  ['readings_yds.js', 'READINGS_YDS'],
  ['readings_yokdil.js', 'READINGS_YOKDIL'],
  ['readings_gre.js', 'READINGS_GRE'],
  ['idioms.js', 'IDIOMS'],
  ['achievements.js', 'ACHIEVEMENTS'],
];

const HEADER =
  '// AUTO-GENERATED by scripts/port_content.mjs — do not edit by hand.\n' +
  '// Source: english-word-coach Android assets (brand: Languago).\n';

mkdirSync(DEST, { recursive: true });

const results = [];

for (const [file, exportName] of FILES) {
  const src = readFileSync(join(SRC, file), 'utf8');
  const head = src.match(/window\.([A-Z0-9_]+)\s*=/);
  if (!head) {
    results.push({ file, status: 'ERROR', detail: 'no window.X assignment found' });
    continue;
  }
  const declared = head[1];
  if (declared !== exportName) {
    results.push({ file, status: 'ERROR', detail: `name mismatch window.${declared} != ${exportName}` });
    continue;
  }
  const windowRefs = (src.match(/window\./g) || []).length;
  // Single, simple substitution of the assignment head only.
  const body = src.replace(`window.${declared} =`, `export const ${declared} =`);
  const out = (body.endsWith('\n') ? HEADER + body : HEADER + body + '\n');
  writeFileSync(join(DEST, file), out);
  results.push({ file, status: 'wrote', detail: `window refs=${windowRefs}, size=${body.length}` });
}

// Sanity-check: import each generated module and confirm the export resolves to
// an object / non-null value so the pages can consume it.
console.log('— converting —');
for (const r of results) console.log(`${r.status.padEnd(6)} ${r.file.padEnd(20)} ${r.detail || ''}`);

let pass = 0;
let fail = 0;
for (const [file, exportName] of FILES) {
  try {
    const mod = await import(pathToFileURL(join(DEST, file)).href);
    const value = mod[exportName];
    if (value == null) {
      fail++;
      console.log(`verify FAIL  ${file}: export ${exportName} is null/undefined`);
    } else {
      const kind = Array.isArray(value) ? `array(${value.length})` : typeof value === 'object' ? 'object' : typeof value;
      pass++;
      console.log(`verify PASS  ${file}: ${exportName} -> ${kind}`);
    }
  } catch (e) {
    fail++;
    console.log(`verify FAIL  ${file}: ${e.message}`);
  }
}

console.log(`\nDone: ${FILES.length} sources parsed, ${pass} verified, ${fail} failed.`);
process.exit(fail ? 1 : 0);