const fs = require('fs');
const path = require('path');

const SITE_DATA = "C:/Users/Samet Tıraşoğlu.DESKTOP-V1NEC06/synth-app/languago-platform/src/data";
const APP_ASSETS = "C:/Users/Samet Tıraşoğlu.DESKTOP-V1NEC06/synth-app/english-word-coach/android/app/src/main/assets";

const LEVELS = [
  { file: 'grammar_a1.js', constName: 'GRAMMAR_A1', mcqFile: 'grammar_mcq_a1.js', mcqConst: 'GRAMMAR_MCQ_A1' },
  { file: 'grammar_a2.js', constName: 'GRAMMAR_A2', mcqFile: 'grammar_mcq_a2.js', mcqConst: 'GRAMMAR_MCQ_A2' },
  { file: 'grammar_b1.js', constName: 'GRAMMAR_B1', mcqFile: 'grammar_mcq_b1.js', mcqConst: 'GRAMMAR_MCQ_B1' },
  { file: 'grammar_b2.js', constName: 'GRAMMAR_B2', mcqFile: 'grammar_mcq_b2.js', mcqConst: 'GRAMMAR_MCQ_B2' },
  { file: 'grammar_c1.js', constName: 'GRAMMAR_C1', mcqFile: 'grammar_mcq_c1.js', mcqConst: 'GRAMMAR_MCQ_C1' },
];

// Generate MCQ array (app format: { q, options, a: index }) from a unit's practice
function generateMcqFromPractice(unit) {
  if (unit.mcq && Array.isArray(unit.mcq) && unit.mcq.length > 0) {
    return unit.mcq;
  }

  const practice = unit.practice || [];
  if (practice.length === 0) return [];

  // Generate 3-4 MCQs by converting practice questions to format: { q, options, a: index }
  const mcqs = [];
  
  // Select a subset of practice questions (skip 0, take next 3-4)
  const start = Math.min(1, Math.floor(practice.length / 2));
  const selected = practice.slice(start, start + 4);

  for (const p of selected) {
    // Get the correct answer(s)
    const correct = Array.isArray(p.a) ? p.a[0] : String(p.a);
    
    // Build options: correct answer + plausible distractors
    // Strategy: use other practice answers as distractors, plus common grammar words
    const otherAnswers = practice
      .filter(op => op !== p)
      .map(op => Array.isArray(op.a) ? op.a[0] : String(op.a));
    
    let options = [correct, ...otherAnswers.filter(a => a !== correct && a)];
    
    // If not enough options, add common distractors based on the correct answer
    const DISTRACTORS = [
      'is', 'are', 'am', 'was', 'were', 'be', 'been', 'being',
      'do', 'does', 'did', 'have', 'has', 'had', 'will', 'would',
      'can', 'could', 'should', 'must', 'may', 'might',
    ];
    
    for (const d of DISTRACTORS) {
      if (options.length >= 4) break;
      if (!options.includes(d)) options.push(d);
    }
    
    options = options.slice(0, 4);
    const aIdx = options.indexOf(correct);
    
    mcqs.push({
      q: p.q,
      options: options,
      a: aIdx >= 0 ? aIdx : 0,
    });
  }
  
  return mcqs;
}

// Load site data
function loadSiteData(filePath, constName) {
  let code = fs.readFileSync(filePath, 'utf8');
  code = code.replace(/\/\/ AUTO-GENERATED by scripts\/port_content\.mjs.*?\.\n/, '');
  code = code.replace(/export\s+const\s+/, 'var ');
  code += '\n;';
  
  eval(code);
  return eval(constName);
}

for (const level of LEVELS) {
  const siteGrammarPath = path.join(SITE_DATA, level.file);
  if (!fs.existsSync(siteGrammarPath)) {
    console.log(`SKIP: ${level.file} not found`);
    continue;
  }

  console.log(`\n--- ${level.file} ---`);
  
  const grammarData = loadSiteData(siteGrammarPath, level.constName);
  if (!grammarData || !grammarData.units) {
    console.log(`  ERROR: Could not load`);
    continue;
  }

  const units = grammarData.units;
  console.log(`  Source units: ${units.length}`);

  // Convert units: keep practice in site format (a: ["answer"]), add mcq arrays
  const convertedUnits = units.map(unit => {
    // Ensure practice has the right format (a as array of strings)
    const practice = (unit.practice || []).map(p => {
      // If already app format (a: index), convert back to array
      if (typeof p.a === 'number' && p.options) {
        return { q: p.q, hint: p.hint || '', a: [p.options[p.a]] };
      }
      // Site format: keep as-is or normalize
      return {
        q: p.q,
        hint: p.hint || '',
        a: Array.isArray(p.a) ? p.a : [String(p.a)],
      };
    });

    // Generate mcq from practice (app format: a = index)
    let mcqs;
    if (unit.mcq && Array.isArray(unit.mcq)) {
      mcqs = unit.mcq;
    } else {
      mcqs = generateMcqFromPractice({ practice: unit.practice, mcq: unit.mcq });
    }

    return {
      id: unit.id,
      title: unit.title,
      short: unit.short || unit.title.split('(')[0].trim(),
      slides: unit.slides || [],
      mistakes: unit.mistakes || [],
      practice: practice,
      mcq: mcqs,
    };
  });

  // Write in app format (window.X)
  const output = `// Languago — ${grammarData.title} (${grammarData.subtitle})\n` +
    `window.${level.constName} = {\n` +
    `  id: "${grammarData.id}",\n` +
    `  title: ${JSON.stringify(grammarData.title)},\n` +
    `  subtitle: ${JSON.stringify(grammarData.subtitle)},\n` +
    `  color: ${JSON.stringify(grammarData.color)},\n` +
    `  units: ${JSON.stringify(convertedUnits, null, 2)}\n` +
    `};\n`;

  fs.writeFileSync(path.join(APP_ASSETS, level.file), output, 'utf8');
  console.log(`  Written: ${level.file} (${convertedUnits.length} units)`);

  // Handle MCQ files
  const siteMcqPath = path.join(SITE_DATA, level.mcqFile);
  if (fs.existsSync(siteMcqPath)) {
    const mcqData = loadSiteData(siteMcqPath, level.mcqConst);
    if (mcqData) {
      // MCQ files use app format: { "id": [{ q, options, a: index, ... }] }
      // Just convert window.X = { ... }
      const mcqOutput = `// Languago — ${level.constName.replace('GRAMMAR_', '').replace('_', ' ')} MCQ\n` +
        `window.${level.mcqConst} = ${JSON.stringify(mcqData, null, 2)};\n`;
      fs.writeFileSync(path.join(APP_ASSETS, level.mcqFile), mcqOutput, 'utf8');
      console.log(`  MCQ Written: ${level.mcqFile}`);
    }
  }
}

console.log('\n=== Grammar sync complete ===');
