plugins {
    id 'com.android.application'
}

android {
    namespace 'com.kingfish.wordcoach'
    compileSdk 34

    defaultConfig {
        applicationId "com.kingfish.wordcoach"
        minSdk 24
        targetSdk 34
        versionCode 11
        versionName "1.9.0"
    }

    signingConfigs {
        release {
            storeFile file("../keystore/wordcoach.keystore")
            storePassword "kingfish2026"
            keyAlias "wordcoach"
            keyPassword "kingfish2026"
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
            signingConfig signingConfigs.release
        }
        debug {
            signingConfig signingConfigs.release
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
