plugins {
    id 'com.android.application'
}

android {
    namespace 'com.languago.app'
    compileSdk 34

    defaultConfig {
        applicationId "com.languago.app"
        minSdk 24
        targetSdk 34
        versionCode 19
        versionName "2.5.1"
    }

    signingConfigs {
        release {
            storeFile file("../keystore/languago.keystore")
            storePassword "languago2026"
            keyAlias "languago"
            keyPassword "languago2026"
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
            signingConfig signingConfigs.release
        }
        debug {
            signingConfig signingConfigs.release
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
